// auth actions
export const LOGIN = 'LOGIN';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_ERROR = 'LOGIN_ERROR';
export const LOGIN_CANCEL = 'LOGIN_CANCEL';

export const LOGOUT = 'LOGOUT';

// scopes actions
export const GET_SCOPES = 'GET_SCOPES';
export const GET_SCOPES_SUCCESS = 'GET_SCOPES_SUCCESS';

export const CREATE_SCOPE = 'CREATE_SCOPE';
export const CREATE_SCOPE_SUCCESS = 'CREATE_SCOPE_SUCCESS';

export const REMOVE_SCOPE = 'REMOVE_SCOPE';
export const REMOVE_SCOPE_SUCCESS = 'REMOVE_SCOPE_SUCCESS';

export const SET_CURRENT_SCOPE = 'SET_CURRENT_SCOPE';
export const SET_CURRENT_SCOPE_SUCCESS = 'SET_CURRENT_SCOPE_SUCCESS';
export const SET_CURRENT_SCOPE_ERROR = 'SET_CURRENT_SCOPE_ERROR';


// directories
export const ADD_DIRECTORY_TO_SCOPE = 'ADD_DIRECTORY_TO_SCOPE';
export const ADD_DIRECTORY_TO_SCOPE_SUCCESS = 'ADD_DIRECTORY_TO_SCOPE_SUCCESS';
export const ADD_DIRECTORY_TO_SCOPE_ERROR = 'ADD_DIRECTORY_TO_SCOPE_ERROR';

export const GET_CURRENT_SCOPE_DIRECTORIES = 'GET_CURRENT_SCOPE_DIRECTORIES';
export const GET_CURRENT_SCOPE_DIRECTORIES_SUCCESS = 'GET_CURRENT_SCOPE_DIRECTORIES_SUCCESS';
export const GET_CURRENT_SCOPE_DIRECTORIES_ERROR = 'GET_CURRENT_SCOPE_DIRECTORIES_ERROR';

export const SET_CURRENT_DIRECTORY = 'SET_CURRENT_DIRECTORY';

export const GET_CURRENT_DIRECTORY_CONTENT = 'GET_CURRENT_DIRECTORY_CONTENT';
export const GET_CURRENT_DIRECTORY_CONTENT_SUCCESS = 'GET_CURRENT_DIRECTORY_CONTENT_SUCCESS';
export const GET_CURRENT_DIRECTORY_CONTENT_ERROR = 'GET_CURRENT_DIRECTORY_CONTENT_ERROR';


// images
export const GET_CURRENT_IMAGE = 'GET_CURRENT_IMAGE';
export const GET_CURRENT_IMAGE_SUCCESS = 'GET_CURRENT_IMAGE_SUCCESS';
export const GET_CURRENT_IMAGE_ERROR = 'GET_CURRENT_IMAGE_ERROR';
export const UNSET_CURRENT_IMAGE = 'UNSET_CURRENT_IMAGE';
